Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection
Section "Monitor"
    Identifier "Monitor0"
    HorizSync 30.0-160.0
    VertRefresh 50.0-75.0
    Option "DPMS" "false"
EndSection
Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration" "true"
    Option "ConnectedMonitor" "HDMI-0"
    Option "CustomEDID" "HDMI-0:/etc/X11/edid4k.bin"
    Option "ModeValidation" "NoMaxPClkCheck,NoEdidMaxPClkCheck,NoMaxSizeCheck,NoHorizSyncCheck,NoVertRefreshCheck,NoVirtualSizeCheck,AllowNonEdidModes,NoEdidHDMI2Check,NoConfigConflictCheck"
EndSection
Section "Screen"
    Identifier "screen"
    Device "nvidia"
    Monitor "Monitor0"
    Option "MetaModes" "HDMI-0: 3840x2160 +0+0"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "3840x2160"
        Virtual 3840 2160
    EndSubSection
EndSection
